### PR TITLE
fix: upgrade to package sets 0.14.5

### PR DESCRIPTION
**Pull request by waynevanson**
- Use `pnpm` to install dependencies locally
- Update docs
- Update spago dependencies
- Use newest package set

I've run the new install instructions which tests the package too and it works!

### CODE REVIEW

**Review by LukaJCB — APPROVED** [review]
That's awesome, thank you! I haven't touched Purescript in years, so I can't say I'll maintain this in any sort of capacity. I'd be happy to transfer any rights to you!

**Comment by waynevanson** [comment]
> 'd be happy to transfer any rights to you!

@LukaJCB I'd love to :)

**Comment by LukaJCB** [comment]
@waynevanson in order for me to transfer the repo to you, you have to delete your fork

**Comment by waynevanson** [comment]
@LukaJCB My fork is now deleted.

**Comment by LukaJCB** [comment]
Requested the transfer

**Comment by waynevanson** [comment]
@LukaJCB Accepted, thank you!

**Pull request merged**
