### PR TITLE
Changes for new version of compiler (0.13.x), dependencies and build system (spago)

### PR DESCRIPTION
**Pull request by MuratOzsoyler**
Having used Rx in both Javascript and C#, I decided to migrate this project to
1. Latest version of compiler (0.13.x)
2. Latest version of dependencies (Eff --> Effect for example)
3. And modern build system (spago)

Just for fun, as a PureScript newcommer :)

If you still interested in this project...

The tests run successfully. But no other tests implemented. So schedulers is not tested. 

Also, as the new `pipe()` method is used extensively as per the RxJS 6.x documents, real world performance may not be remarkable. This should be bencmarked.

### CODE REVIEW

**Comment by LukaJCB** [comment]
This is so cool, thanks a ton for this! I think you might also need to have a look at the `.travis.yml` to run the correct command. :) 
I don't have a lot of time for PureScript these days, I'd be happy to give you write access to the repo if you'd like!

**Comment by MuratOzsoyler** [comment]
Yes, I noticed just after I created the pull request. I'll return in a moment.

**Comment by LukaJCB** [comment]
Awesome, LGTM!

**Comment by MuratOzsoyler** [comment]
Thank you!

**Pull request merged**
